[package]
edition = "2021"
name = "compiler"
version = "0.1.0"

[dependencies]
anyhow = "1.0.58"
cst = {path = "../cst"}
parser = {path = "../parser"}
raw_index = {path = "../raw_index"}
resolved_index = {path = "../resolved_index"}
syntax = {path = "../syntax"}
text-size = "1.1.0"
