[package]
edition = "2021"
name = "resolved_index"
version = "0.0.0"

[dependencies]
arena = {path = "../arena"}
raw_index = {path = "../raw_index"}
text-size = "1.1.0"

[dev-dependencies]
parser = {path = "../parser"}
test_utils = {path = "../test_utils"}
