[package]
edition = "2021"
name = "ast"
version = "0.0.0"

[dependencies]
arena = {path = "../arena"}
syntax = {path = "../syntax"}
text-size = "1.1.0"

[dev-dependencies]
parser = {path = "../parser"}
test_utils = {path = "../test_utils"}
