[package]
edition = "2021"
name = "parser"
version = "0.0.0"

[dependencies]
lexer = {path = "../lexer"}
syntax = {path = "../syntax"}
text-size = "1.1.0"

[dev-dependencies]
test_utils = {path = "../test_utils"}
